# SPDX-FileCopyrightText: 2019 Tuomas Siipola
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "pio"
version = "0.1.5"
authors = ["Tuomas Siipola <tuomas@zpl.fi>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
dssim = "2.9.9"
imgref = "1.3.5"
mozjpeg = "0.8.14"
rgb = "0.8.13"
lodepng = "2.4.2"
imagequant = "2.11.9"
libwebp-sys = "0.2.0"
clap = "2.33.0"
