name: Rust

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: sudo apt install musl-tools -y
      if: runner.os == 'Linux'
    - name: Build
      run: rustup target add x86_64-unknown-linux-musl
      if: runner.os == 'Linux'
    - name: Build
      run: rustup target add x86_64-apple-darwin
      if: runner.os == 'macOS'
    - name: Build
      run: rustup component add clippy rustfmt
    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-musl
      if: runner.os == 'Linux'
    - name: Build
      run: cargo build --release --target=x86_64-apple-darwin
      if: runner.os == 'macOS'
    - name: Build
      run: cargo clippy
    - name: Build
      run: cargo fmt --all -- --check
    - uses: actions/upload-artifact@v1
      if: runner.os == 'macOS'
      with:
        name: pio-x86_64-apple-darwin
        path: target/x86_64-apple-darwin/release/pio
    - uses: actions/upload-artifact@v1
      if: runner.os == 'Linux'
      with:
        name: pio-x86_64-unknown-linux-musl
        path: target/x86_64-unknown-linux-musl/release/pio
    - name: Move
      if: runner.os == 'Linux'
      run: mv target/x86_64-unknown-linux-musl/release/pio pio-x86_64-unknown-linux-musl
    - name: Move
      if: runner.os == 'macOS'
      run: mv target/x86_64-apple-darwin/release/pio pio-x86_64-apple-darwin
    - name: Release (Mac)
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: pio-x86_64-apple-darwin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release (Linux)
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: pio-x86_64-unknown-linux-musl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
